### ISSUE TITLE
Node exits during syncing

### ISSUE THREAD

**Issue by mfaizan1** [Sifchain/sifnode#1939]
**Current behavior**
During syncing node exits at block height `2976499`

apparently there is some upgrade needed but it fails and makes the node to exit

**Expected behavior**
node should keep syncing 

**Steps to reproduce**
start a new node using steps in readme for betanet

Identify exact point in reproduction steps where expectation is violated

```2021-09-29T07:19:17.039977089Z 7:19AM ERR UPGRADE "0.9.5" NEEDED at height: 2976500: {"binaries":{"linux/amd64":"https://github.com/Sifchain/sifnode/releases/download/betanet-0.9.5/sifnoded-betanet-0.9.5-linux-amd64.zip?checksum=4d7432b48e73c736cdb62edfc8771fdad7842ed66852b9ae5269fca1ad2f69a9"}}
2021-09-29T07:19:19.734440615Z 7:19AM INF starting ABCI with Tendermint
2021-09-29T07:19:21.108210997Z 7:19AM INF Starting multiAppConn service impl=multiAppConn module=proxy
2021-09-29T07:19:21.108262764Z 7:19AM INF Starting localClient service connection=query impl=localClient module=abci-client
2021-09-29T07:19:21.108282741Z 7:19AM INF Starting localClient service connection=snapshot impl=localClient module=abci-client
2021-09-29T07:19:21.108286889Z 7:19AM INF Starting localClient service connection=mempool impl=localClient module=abci-client
2021-09-29T07:19:21.108290746Z 7:19AM INF Starting localClient service connection=consensus impl=localClient module=abci-client
2021-09-29T07:19:21.108294312Z 7:19AM INF Starting EventBus service impl=EventBus module=events
2021-09-29T07:19:21.108298140Z 7:19AM INF Starting PubSub service impl=PubSub module=pubsub
2021-09-29T07:19:21.329989601Z 7:19AM INF Starting IndexerService service impl=IndexerService module=txindex
2021-09-29T07:19:21.330187280Z 7:19AM INF ABCI Handshake App Info hash="��|�\x1c\vjư̕��\x1a\b��ȼ��J�ƕ�uJYcN�" height=2976499 module=consensus protocol-version=0 software-version=
2021-09-29T07:19:21.330333172Z 7:19AM INF ABCI Replay Blocks appHeight=2976499 module=consensus stateHeight=2976499 storeHeight=2976500
2021-09-29T07:19:21.330338602Z 7:19AM INF Replay last block using real app module=consensus
2021-09-29T07:19:21.553371553Z 7:19AM INF applying upgrade "0.9.5" at height: 2976500
2021-09-29T07:19:21.553409164Z 7:19AM INF Running upgrade handler for 0.9.5 with new store tokenregistry-2
2021-09-29T07:19:21.583926777Z 7:19AM INF executed block height=2976500 module=consensus num_invalid_txs=0 num_valid_txs=0
2021-09-29T07:19:21.646980824Z panic: cannot delete latest saved version (1)
2021-09-29T07:19:21.647144529Z 
2021-09-29T07:19:21.647156150Z goroutine 1 [running]:
2021-09-29T07:19:21.647232733Z github.com/cosmos/cosmos-sdk/store/rootmulti.(*Store).pruneStores(0xc000d66280)
2021-09-29T07:19:21.647260936Z 	/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.42.9/store/rootmulti/store.go:388 +0x268
2021-09-29T07:19:21.647264843Z github.com/cosmos/cosmos-sdk/store/rootmulti.(*Store).Commit(0xc000d66280, 0x2d6af4, 0x0, 0xc00013dce0, 0x71374491c28a2f98)
2021-09-29T07:19:21.647267578Z 	/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.42.9/store/rootmulti/store.go:362 +0x1c6
2021-09-29T07:19:21.647460388Z github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).Commit(0xc000f21520, 0x0, 0x0, 0x0, 0x0)
2021-09-29T07:19:21.647528023Z 	/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.42.9/baseapp/abci.go:305 +0x29c
2021-09-29T07:19:21.647533985Z github.com/tendermint/tendermint/abci/client.(*localClient).CommitSync(0xc000d92960, 0x0, 0x0, 0x0)
2021-09-29T07:19:21.647537020Z 	/go/pkg/mod/github.com/tendermint/tendermint@v0.34.11/abci/client/local_client.go:258 +0xab
2021-09-29T07:19:21.647540176Z github.com/tendermint/tendermint/proxy.(*appConnConsensus).CommitSync(0xc00056dd50, 0x0, 0x0, 0xc0034606c0)
2021-09-29T07:19:21.647543182Z 	/go/pkg/mod/github.com/tendermint/tendermint@v0.34.11/proxy/app_conn.go:93 +0x33
2021-09-29T07:19:21.647578677Z github.com/tendermint/tendermint/state.(*BlockExecutor).Commit(0xc00013f340, 0xb, 0x0, 0x0, 0x0, 0xc000f58050, 0xa, 0x2701d3, 0x2d6af4, 0xc00278cfa0, ...)
2021-09-29T07:19:21.647582805Z 	/go/pkg/mod/github.com/tendermint/tendermint@v0.34.11/state/execution.go:228 +0x23f
2021-09-29T07:19:21.647585861Z github.com/tendermint/tendermint/state.(*BlockExecutor).ApplyBlock(0xc00013f340, 0xb, 0x0, 0x0, 0x0, 0xc000f58050, 0xa, 0x2701d3, 0x2d6af4, 0xc00278cfa0, ...)
2021-09-29T07:19:21.647588907Z 	/go/pkg/mod/github.com/tendermint/tendermint@v0.34.11/state/execution.go:180 +0x6c5
2021-09-29T07:19:21.647592002Z github.com/tendermint/tendermint/consensus.(*Handshaker).replayBlock(0xc0061c4458, 0xb, 0x0, 0x0, 0x0, 0xc000f58050, 0xa, 0x2701d3, 0x2d6af3, 0xc0020febe0, ...)
2021-09-29T07:19:21.647595118Z 	/go/pkg/mod/github.com/tendermint/tendermint@v0.34.11/consensus/replay.go:503 +0x268
2021-09-29T07:19:21.647598194Z github.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(0xc002e56458, 0xb, 0x0, 0x0, 0x0, 0xc000f58050, 0xa, 0x2701d3, 0x2d6af3, 0xc0020febe0, ...)
2021-09-29T07:19:21.647601380Z 	/go/pkg/mod/github.com/tendermint/tendermint@v0.34.11/consensus/replay.go:416 +0xd18
2021-09-29T07:19:21.647604446Z github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0xc0061c4458, 0x21cac40, 0xc0001020d0, 0x1, 0x1)
2021-09-29T07:19:21.647607662Z 	/go/pkg/mod/github.com/tendermint/tendermint@v0.34.11/consensus/replay.go:268 +0x478
2021-09-29T07:19:21.647610557Z github.com/tendermint/tendermint/node.doHandshake(0x21c6b60, 0xc0026dfbf0, 0xb, 0x0, 0x0, 0x0, 0xc000f58050, 0xa, 0x2701d3, 0x2d6af3, ...)
2021-09-29T07:19:21.647618753Z 	/go/pkg/mod/github.com/tendermint/tendermint@v0.34.11/node/node.go:308 +0x1d8
2021-09-29T07:19:21.647625165Z github.com/tendermint/tendermint/node.NewNode(0xc000dff2c0, 0x21a7060, 0xc000d66e60, 0xc00056c220, 0x216f1e0, 0xc0000c3e20, 0xc00056c2e0, 0x1f973e8, 0xc00056c4f0, 0x21b0da0, ...)
2021-09-29T07:19:21.647628571Z 	/go/pkg/mod/github.com/tendermint/tendermint@v0.34.11/node/node.go:715 +0x2025
2021-09-29T07:19:21.647669737Z github.com/cosmos/cosmos-sdk/server.startInProcess(0xc000f12140, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x21b9040, 0xc000de17a0, ...)
2021-09-29T07:19:21.647673965Z 	/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.42.9/server/start.go:244 +0x565
2021-09-29T07:19:21.647676911Z github.com/cosmos/cosmos-sdk/server.StartCmd.func2(0xc000e69680, 0xc000ec8c40, 0x0, 0x4, 0x0, 0x0)
2021-09-29T07:19:21.647686909Z 	/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.42.9/server/start.go:120 +0x189
2021-09-29T07:19:21.647689935Z github.com/spf13/cobra.(*Command).execute(0xc000e69680, 0xc000ec8c00, 0x4, 0x4, 0xc000e69680, 0xc000ec8c00)
2021-09-29T07:19:21.647692800Z 	/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:852 +0x47c
2021-09-29T07:19:21.647695706Z github.com/spf13/cobra.(*Command).ExecuteC(0xc000da9900, 0x0, 0x0, 0xc000dee2a0)
2021-09-29T07:19:21.647698531Z 	/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x375
2021-09-29T07:19:21.647701457Z github.com/spf13/cobra.(*Command).Execute(...)
2021-09-29T07:19:21.647704232Z 	/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
2021-09-29T07:19:21.647707027Z github.com/spf13/cobra.(*Command).ExecuteContext(...)
2021-09-29T07:19:21.647709792Z 	/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:890
2021-09-29T07:19:21.647712588Z github.com/cosmos/cosmos-sdk/server/cmd.Execute(0xc000da9900, 0xc000dee2a0, 0xf, 0x21ccb80, 0xc000de17a0)
2021-09-29T07:19:21.647715473Z 	/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.42.9/server/cmd/execute.go:36 +0x265
2021-09-29T07:19:21.647718348Z main.main()
2021-09-29T07:19:21.647721063Z 	/github/workspace/cmd/sifnoded/main.go:18 +0x5e
2021-09-29T07:19:21.658300254Z exit status 2
```

**Additional context**
if i try to run node again using `rake "sifnode:standalone:boot...` i get this error
```Starting sifchain-1_sifnode_1 ... done
Attaching to sifchain-1_sifnode_1
sifnode_1  | 8:12AM INF starting ABCI with Tendermint
sifnode_1  | 8:12AM INF Starting multiAppConn service impl=multiAppConn module=proxy
sifnode_1  | 8:12AM INF Starting localClient service connection=query impl=localClient module=abci-client
sifnode_1  | 8:12AM INF Starting localClient service connection=snapshot impl=localClient module=abci-client
sifnode_1  | 8:12AM INF Starting localClient service connection=mempool impl=localClient module=abci-client
sifnode_1  | 8:12AM INF Starting localClient service connection=consensus impl=localClient module=abci-client
sifnode_1  | 8:12AM INF Starting EventBus service impl=EventBus module=events
sifnode_1  | 8:12AM INF Starting PubSub service impl=PubSub module=pubsub
sifnode_1  | 8:12AM INF Starting IndexerService service impl=IndexerService module=txindex
sifnode_1  | 8:12AM INF ABCI Handshake App Info hash="��|�\x1c\vjư̕��\x1a\b��ȼ��J�ƕ�uJYcN�" height=2976499 module=consensus protocol-version=0 software-version=
sifnode_1  | 8:12AM INF ABCI Replay Blocks appHeight=2976499 module=consensus stateHeight=2976499 storeHeight=2976500
sifnode_1  | 8:12AM INF Replay last block using real app module=consensus
sifnode_1  | 8:12AM INF applying upgrade "0.9.5" at height: 2976500
sifnode_1  | 8:12AM INF Running upgrade handler for 0.9.5 with new store tokenregistry-2
sifnode_1  | 8:12AM INF executed block height=2976500 module=consensus num_invalid_txs=0 num_valid_txs=0
sifnode_1  | panic: cannot delete latest saved version (5)
sifnode_1  | 
sifnode_1  | goroutine 1 [running]:
sifnode_1  | github.com/cosmos/cosmos-sdk/store/rootmulti.(*Store).pruneStores(0xc0000f4280)
sifnode_1  | 	/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.42.9/store/rootmulti/store.go:388 +0x268
sifnode_1  | github.com/cosmos/cosmos-sdk/store/rootmulti.(*Store).Commit(0xc0000f4280, 0x2d6af4, 0x0, 0xc007e166e0, 0x71374491c28a2f98)
sifnode_1  | 	/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.42.9/store/rootmulti/store.go:362 +0x1c6
sifnode_1  | github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).Commit(0xc000112340, 0x0, 0x0, 0x0, 0x0)
sifnode_1  | 	/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.42.9/baseapp/abci.go:305 +0x29c
sifnode_1  | github.com/tendermint/tendermint/abci/client.(*localClient).CommitSync(0xc00183b200, 0x0, 0x0, 0x0)
sifnode_1  | 	/go/pkg/mod/github.com/tendermint/tendermint@v0.34.11/abci/client/local_client.go:258 +0xab
sifnode_1  | github.com/tendermint/tendermint/proxy.(*appConnConsensus).CommitSync(0xc000ec4dc0, 0x0, 0x0, 0xc001644c00)
sifnode_1  | 	/go/pkg/mod/github.com/tendermint/tendermint@v0.34.11/proxy/app_conn.go:93 +0x33
sifnode_1  | github.com/tendermint/tendermint/state.(*BlockExecutor).Commit(0xc0015881c0, 0xb, 0x0, 0x0, 0x0, 0xc0011a8b10, 0xa, 0x2701d3, 0x2d6af4, 0xc0016f1e80, ...)
sifnode_1  | 	/go/pkg/mod/github.com/tendermint/tendermint@v0.34.11/state/execution.go:228 +0x23f
sifnode_1  | github.com/tendermint/tendermint/state.(*BlockExecutor).ApplyBlock(0xc0015881c0, 0xb, 0x0, 0x0, 0x0, 0xc0011a8b10, 0xa, 0x2701d3, 0x2d6af4, 0xc0016f1e80, ...)
sifnode_1  | 	/go/pkg/mod/github.com/tendermint/tendermint@v0.34.11/state/execution.go:180 +0x6c5
sifnode_1  | github.com/tendermint/tendermint/consensus.(*Handshaker).replayBlock(0xc00170e458, 0xb, 0x0, 0x0, 0x0, 0xc0011a8b10, 0xa, 0x2701d3, 0x2d6af3, 0xc000f65140, ...)
sifnode_1  | 	/go/pkg/mod/github.com/tendermint/tendermint@v0.34.11/consensus/replay.go:503 +0x268
sifnode_1  | github.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(0xc001222458, 0xb, 0x0, 0x0, 0x0, 0xc0011a8b10, 0xa, 0x2701d3, 0x2d6af3, 0xc000f65140, ...)
sifnode_1  | 	/go/pkg/mod/github.com/tendermint/tendermint@v0.34.11/consensus/replay.go:416 +0xd18
sifnode_1  | github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0xc00170e458, 0x21cac40, 0xc0004d9380, 0x1, 0x1)
sifnode_1  | 	/go/pkg/mod/github.com/tendermint/tendermint@v0.34.11/consensus/replay.go:268 +0x478
sifnode_1  | github.com/tendermint/tendermint/node.doHandshake(0x21c6b60, 0xc0011db040, 0xb, 0x0, 0x0, 0x0, 0xc0011a8b10, 0xa, 0x2701d3, 0x2d6af3, ...)
sifnode_1  | 	/go/pkg/mod/github.com/tendermint/tendermint@v0.34.11/node/node.go:308 +0x1d8
sifnode_1  | github.com/tendermint/tendermint/node.NewNode(0xc000f5d2c0, 0x21a7060, 0xc0000f4c80, 0xc0004ef130, 0x216f1e0, 0xc00334ae60, 0xc0004ef1a0, 0x1f973e8, 0xc0004ef290, 0x21b0da0, ...)
sifnode_1  | 	/go/pkg/mod/github.com/tendermint/tendermint@v0.34.11/node/node.go:715 +0x2025
sifnode_1  | github.com/cosmos/cosmos-sdk/server.startInProcess(0xc000fd0fe0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x21b9040, 0xc000f0ba00, ...)
sifnode_1  | 	/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.42.9/server/start.go:244 +0x565
sifnode_1  | github.com/cosmos/cosmos-sdk/server.StartCmd.func2(0xc000f9b680, 0xc0010268c0, 0x0, 0x4, 0x0, 0x0)
sifnode_1  | 	/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.42.9/server/start.go:120 +0x189
sifnode_1  | github.com/spf13/cobra.(*Command).execute(0xc000f9b680, 0xc001026880, 0x4, 0x4, 0xc000f9b680, 0xc001026880)
sifnode_1  | 	/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:852 +0x47c
sifnode_1  | github.com/spf13/cobra.(*Command).ExecuteC(0xc000ec7900, 0x0, 0x0, 0xc000f1c140)
sifnode_1  | 	/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x375
sifnode_1  | github.com/spf13/cobra.(*Command).Execute(...)
sifnode_1  | 	/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
sifnode_1  | github.com/spf13/cobra.(*Command).ExecuteContext(...)
sifnode_1  | 	/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:890
sifnode_1  | github.com/cosmos/cosmos-sdk/server/cmd.Execute(0xc000ec7900, 0xc000f1c140, 0xf, 0x21ccb80, 0xc000f0ba00)
sifnode_1  | 	/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.42.9/server/cmd/execute.go:36 +0x265
sifnode_1  | main.main()
sifnode_1  | 	/github/workspace/cmd/sifnoded/main.go:18 +0x5e
sifnode_1  | exit status 2
sifchain-1_sifnode_1 exited with code 1```

**Comment by intl-man** [comment]
This is a known issue, with the upgrade to 0.9.5. 

Follow the instructions here:

https://github.com/Sifchain/sifchain-validators/blob/master/docs/setup/standalone/manual.md

for spinning up a new node with a snapshot.
