### ISSUE TITLE
Devenv stuck at deploy contract

### ISSUE THREAD

**Issue by smartyalgo** [Sifchain/sifnode#2112]
Standing up a devenv stack would fail at contract deployment step, 
```
$ npx hardhat run scripts/deploy_contracts.ts --network localhost
No need to generate any newer typings.
/Users/sifchain_michael/Projects/workspace/sifnode/smart-contracts/node_modules/hardhat/src/internal/core/providers/http.ts:176
        throw new HardhatError(
              ^
HardhatError: HH108: Cannot connect to the network localhost.
Please make sure your node is running, and check your internet connection and networks config
    at HttpProvider._fetchJsonRpcResponse (/Users/sifchain_michael/Projects/workspace/sifnode/smart-contracts/node_modules/hardhat/src/internal/core/providers/http.ts:176:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async HttpProvider.request (/Users/sifchain_michael/Projects/workspace/sifnode/smart-contracts/node_modules/hardhat/src/internal/core/providers/http.ts:55:29)
    at async GanacheGasMultiplierProvider._isGanache (/Users/sifchain_michael/Projects/workspace/sifnode/smart-contracts/node_modules/hardhat/src/internal/core/providers/gas-providers.ts:315:30)
    at async GanacheGasMultiplierProvider.request (/Users/sifchain_michael/Projects/workspace/sifnode/smart-contracts/node_modules/hardhat/src/internal/core/providers/gas-providers.ts:304:23)
    at async EthersProviderWrapper.send (/Users/sifchain_michael/Projects/workspace/sifnode/smart-contracts/node_modules/@nomiclabs/hardhat-ethers/src/internal/ethers-provider-wrapper.ts:13:20)
    at async Object.getSigners (/Users/sifchain_michael/Projects/workspace/sifnode/smart-contracts/node_modules/@nomiclabs/hardhat-ethers/src/internal/helpers.ts:23:20) {
  parent: FetchError: request to http://127.0.0.1:8545/ failed, reason: connect ECONNREFUSED 127.0.0.1:8545
      at ClientRequest.<anonymous> (/Users/sifchain_michael/Projects/workspace/sifnode/smart-contracts/node_modules/node-fetch/lib/index.js:1483:11)
      at ClientRequest.emit (node:events:390:28)
      at ClientRequest.emit (node:domain:475:12)
      at Socket.socketErrorListener (node:_http_client:447:9)
      at Socket.emit (node:events:390:28)
      at Socket.emit (node:domain:475:12)
      at emitErrorNT (node:internal/streams/destroy:164:8)
      at emitErrorCloseNT (node:internal/streams/destroy:129:3)
      at processTicksAndRejections (node:internal/process/task_queues:83:21) {
    type: 'system',
    errno: 'ECONNREFUSED',
    code: 'ECONNREFUSED'
  },
  errorDescriptor: {
    number: 108,
    message: 'Cannot connect to the network %network%.\n' +
      'Please make sure your node is running, and check your internet connection and networks config',
    title: 'Cannot connect to the network',
    description: 'Cannot connect to the network.\n' +
      '\n' +
      'Please make sure your node is running, and check your internet connection and networks config.',
    shouldBeReported: false
  },
  number: 108,
  messageArguments: { network: 'localhost' },
  _isHardhatError: true
}
```

Even if hardhat node is deployed

We suspect an up-to-date set of dependencies is causing the issue. This is because after downgrading dependencies versions to match last-known set, this issue goes away

Deliverable
- Reproduce/Verify the issue
- If confirmed is due to versioning, lock version and monitor for relevant fix release

**Comment by pandaring2you** [comment]
Review priority at next sprint planning meeting.

**Comment by pandaring2you** [comment]
if we move to siftool - not an issue.

**Comment by smartyalgo** [comment]
Moving to siftool, this ticket is no longer relevant
