### ISSUE TITLE
Not able to create tokens in new DevNet environment

### ISSUE THREAD

**Issue by sheokapr** [Sifchain/sifnode#2193]
**Steps to Reproduce:**
1. Created this configuration file to include rpc end-points, operator addresses etc. (confirmed with @intl-man operator address and its pvt key is correct)
export BASEDIR=~/sifnode
export DEPLOYMENT_NAME=sifchain-devnet-1
export OPERATOR_ADDRESS=0x1e0220B251eE648C7F3B6Fc31E6d309141f2e464
export ETHEREUM_ADDRESS=0x50cAdE6ec896E675644742188ba885d8FCC25039
export ROWAN_SOURCE=sif1d0q6q6afvzk3whu6cy338yth64vau78r43fsuh
export ETHEREUM_NETWORK=ropsten
export ETHEREUM_NETWORK_ID=3
export SIFNODE=tcp://rpc-devnet.sifchain.finance:80
export INFURA_PROJECT_ID=c413023ff7944d21b694664b31a52faf
export ETHEREUM_PRIVATE_KEY=REMOVED HERE FOR SECURITY REASONS
export OPERATOR_PRIVATE_KEY=REMOVED FOR SECURITY REASONS
. $BASEDIR/test/integration/environment_setup.sh

2. source swingset.sh (this echoed some pegging commands)
3. Ran this token creation script - ~/sifnode/test/integration$ TOKENS_FILE=assets.json python3 -m pytest --color=yes -x -olog_cli=true -olog_level=DEBUG -v -olog_file=vagrant/data/pytest.log **src/py/token_setup.py**

Script is throwing below error. @intl-man reckons this could be due to this script might be calling infura instead of alchemy end-points and failing. Infura is decommissioned, so it should use alchemy end-point.

**Error is:**
command_line = 'yarn -s --cwd /home/punix/sifnode/smart-contracts integrationtest:whitelistedTokens --bridgebank_address 0x96DC6f02C6...tracts/deployments/sifchain-devnet-1 --ethereum_private_key_env_var "ETHEREUM_PRIVATE_KEY" --ethereum_network ropsten '

    def get_shell_output(command_line):
        cmdfile.write(command_line)
        if sifnoded_binary in command_line and not "q auth account" in command_line:
            time.sleep(2)
        logging.debug(f"execute shell command:\n{command_line}")
        sub = subprocess.run(command_line, shell=True, capture_output=True)
        stdout_string = sub.stdout.decode("utf-8").rstrip()
        stderr_string = sub.stderr.decode("utf-8").rstrip()
        logging.debug(f"execute shell command stdout:\n{stdout_string}\n")
        if stderr_string:
            logging.debug(f"\nexecute shell command stderr:\n{stderr_string}")
        if sub.returncode != 0:
>           raise Exception(
                f"error running command: {sub.returncode} for command\n{command_line}\nstdout:\n{stdout_string}\nstderr:\n{stderr_string}")
E           Exception: error running command: 7 for command
E           yarn -s --cwd /home/punix/sifnode/smart-contracts integrationtest:whitelistedTokens --bridgebank_address 0x96DC6f02C66Bbf2dfbA934b8DafE7B2c08715A73 --json_path /home/punix/sifnode/smart-contracts/deployments/sifchain-devnet-1 --ethereum_private_key_env_var "ETHEREUM_PRIVATE_KEY" --ethereum_network ropsten
E           stdout:
E           > Warning: possible unsupported (undocumented in help) command line option(s): --bridgebank_address,--json_path,--ethereum_private_key_env_var,--ethereum_network
E           Using network 'ganache'.
E
E           {"error":{},"level":"error","message":"uncaughtException: PollingBlockTracker - encountered an error while attempting to update latest block:\nError: Unknown Error: {\"jsonrpc\": \"2.0\", \"id\": 1, \"error\": {\"code\": -32000, \"message\": \"Must be authenticated!\"}}\n    at Request._callback (/home/punix/sifnode/smart-contracts/node_modules/@trufflesuite/web3-provider-engine/subproviders/rpc.js:57:23)\n    at Request.self.callback (/home/punix/sifnode/smart-contracts/node_modules/request/request.js:185:22)\n    at Request.emit (events.js:400:28)\n    at Request.<anonymous> (/home/punix/sifnode/smart-contracts/node_modules/request/request.js:1154:10)\n    at Request.emit (events.js:400:28)\n    at IncomingMessage.<anonymous> (/home/punix/sifnode/smart-contracts/node_modules/request/request.js:1076:12)\n    at Object.onceWrapper (events.js:519:28)\n    at IncomingMessage.emit (events.js:412:35)\n    at endReadableNT (internal/streams/readable.js:1334:12)\n    at processTicksAndRejections (internal/process/task_queues.js:82:21)\nError: PollingBlockTracker - encountered an error while attempting to update latest block:\nError: Unknown Error: {\"jsonrpc\": \"2.0\", \"id\": 1, \"error\": {\"code\": -32000, \"message\": \"Must be authenticated!\"}}\n    at Request._callback (/home/punix/sifnode/smart-contracts/node_modules/@trufflesuite/web3-provider-engine/subproviders/rpc.js:57:23)\n    at Request.self.callback (/home/punix/sifnode/smart-contracts/node_modules/request/request.js:185:22)\n    at Request.emit (events.js:400:28)\n    at Request.<anonymous> (/home/punix/sifnode/smart-contracts/node_modules/request/request.js:1154:10)\n    at Request.emit (events.js:400:28)\n    at IncomingMessage.<anonymous> (/home/punix/sifnode/smart-contracts/node_modules/request/request.js:1076:12)\n    at Object.onceWrapper (events.js:519:28)\n    at IncomingMessage.emit (events.js:412:35)\n    at endReadableNT (internal/streams/readable.js:1334:12)\n    at processTicksAndRejections (internal/process/task_queues.js:82:21)\n    at PollingBlockTracker._performSync (/home/punix/sifnode/smart-contracts/node_modules/eth-block-tracker/src/polling.js:51:24)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)","stack":"Error: PollingBlockTracker - encountered an error while attempting to update latest block:\nError: Unknown Error: {\"jsonrpc\": \"2.0\", \"id\": 1, \"error\": {\"code\": -32000, \"message\": \"Must be authenticated!\"}}\n    at Request._callback (/home/punix/sifnode/smart-contracts/node_modules/@trufflesuite/web3-provider-engine/subproviders/rpc.js:57:23)\n    at Request.self.callback (/home/punix/sifnode/smart-contracts/node_modules/request/request.js:185:22)\n    at Request.emit (events.js:400:28)\n    at Request.<anonymous> (/home/punix/sifnode/smart-contracts/node_modules/request/request.js:1154:10)\n    at Request.emit (events.js:400:28)\n    at IncomingMessage.<anonymous> (/home/punix/sifnode/smart-contracts/node_modules/request/request.js:1076:12)\n    at Object.onceWrapper (events.js:519:28)\n    at IncomingMessage.emit (events.js:412:35)\n    at endReadableNT (internal/streams/readable.js:1334:12)\n    at processTicksAndRejections (internal/process/task_queues.js:82:21)\n    at PollingBlockTracker._performSync (/home/punix/sifnode/smart-contracts/node_modules/eth-block-tracker/src/polling.js:51:24)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)","exception":true,"date":"Wed Nov 17 2021 17:33:00 GMT+0000 (Greenwich Mean Time)","process":{"pid":20703,"uid":1000,"gid":1000,"cwd":"/home/punix/sifnode/smart-contracts","execPath":"/usr/bin/node","version":"v14.18.1","argv":["/usr/bin/node","/home/punix/sifnode/smart-contracts/node_modules/.bin/truffle","exec","scripts/test/whitelistedTokens.js","--bridgebank_address","0x96DC6f02C66Bbf2dfbA934b8DafE7B2c08715A73","--json_path","/home/punix/sifnode/smart-contracts/deployments/sifchain-devnet-1","--ethereum_private_key_env_var","ETHEREUM_PRIVATE_KEY","--ethereum_network","ropsten"],"memoryUsage":{"rss":345657344,"heapTotal":269131776,"heapUsed":240268448,"external":19122405,"arrayBuffers":17472435}},"os":{"loadavg":[0,0.02,0],"uptime":11672.79},"trace":[{"column":23,"file":"/home/punix/sifnode/smart-contracts/node_modules/@trufflesuite/web3-provider-engine/subproviders/rpc.js","function":"Request._callback","line":57,"method":"_callback","native":false},{"column":22,"file":"/home/punix/sifnode/smart-contracts/node_modules/request/request.js","function":"Request.self.callback","line":185,"method":"callback","native":false},{"column":28,"file":"events.js","function":"Request.emit","line":400,"method":"emit","native":false},{"column":10,"file":"/home/punix/sifnode/smart-contracts/node_modules/request/request.js","function":null,"line":1154,"method":null,"native":false},{"column":28,"file":"events.js","function":"Request.emit","line":400,"method":"emit","native":false},{"column":12,"file":"/home/punix/sifnode/smart-contracts/node_modules/request/request.js","function":null,"line":1076,"method":null,"native":false},{"column":28,"file":"events.js","function":"Object.onceWrapper","line":519,"method":"onceWrapper","native":false},{"column":35,"file":"events.js","function":"IncomingMessage.emit","line":412,"method":"emit","native":false},{"column":12,"file":"internal/streams/readable.js","function":"endReadableNT","line":1334,"method":null,"native":false},{"column":21,"file":"internal/process/task_queues.js","function":"processTicksAndRejections","line":82,"method":null,"native":false},{"column":24,"file":"/home/punix/sifnode/smart-contracts/node_modules/eth-block-tracker/src/polling.js","function":"PollingBlockTracker._performSync","line":51,"method":"_performSync","native":false},{"column":5,"file":"internal/process/task_queues.js","function":"processTicksAndRejections","line":95,"method":null,"native":false}]}
E           stderr:
E           /home/punix/sifnode/smart-contracts/node_modules/winston/lib/winston/logger.js:307
E                 throw ex;
E                 ^
E
E           NodeError: write after end
E               at writeAfterEnd (/home/punix/sifnode/smart-contracts/node_modules/winston/node_modules/readable-stream/lib/_stream_writable.js:261:12)
E               at PassThrough.Writable.write (/home/punix/sifnode/smart-contracts/node_modules/winston/node_modules/readable-stream/lib/_stream_writable.js:305:21)
E               at File.log (/home/punix/sifnode/smart-contracts/node_modules/winston/lib/winston/transports/file.js:185:34)
E               at ExceptionStream._write (/home/punix/sifnode/smart-contracts/node_modules/winston/lib/winston/exception-stream.js:48:29)
E               at doWrite (/home/punix/sifnode/smart-contracts/node_modules/winston/node_modules/readable-stream/lib/_stream_writable.js:409:139)
E               at writeOrBuffer (/home/punix/sifnode/smart-contracts/node_modules/winston/node_modules/readable-stream/lib/_stream_writable.js:398:5)
E               at ExceptionStream.Writable.write (/home/punix/sifnode/smart-contracts/node_modules/winston/node_modules/readable-stream/lib/_stream_writable.js:307:11)
E               at DerivedLogger.ondata (/home/punix/sifnode/smart-contracts/node_modules/winston/node_modules/readable-stream/lib/_stream_readable.js:681:20)
E               at DerivedLogger.emit (events.js:412:35)
E               at addChunk (/home/punix/sifnode/smart-contracts/node_modules/winston/node_modules/readable-stream/lib/_stream_readable.js:298:12)
E               at readableAddChunk (/home/punix/sifnode/smart-contracts/node_modules/winston/node_modules/readable-stream/lib/_stream_readable.js:280:11)
E               at DerivedLogger.Readable.push (/home/punix/sifnode/smart-contracts/node_modules/winston/node_modules/readable-stream/lib/_stream_readable.js:241:10)
E               at DerivedLogger.Transform.push (/home/punix/sifnode/smart-contracts/node_modules/winston/node_modules/readable-stream/lib/_stream_transform.js:139:32)
E               at DerivedLogger._transform (/home/punix/sifnode/smart-contracts/node_modules/winston/lib/winston/logger.js:305:12)
E               at DerivedLogger.Transform._read (/home/punix/sifnode/smart-contracts/node_modules/winston/node_modules/readable-stream/lib/_stream_transform.js:177:10)
E               at DerivedLogger.Transform._write (/home/punix/sifnode/smart-contracts/node_modules/winston/node_modules/readable-stream/lib/_stream_transform.js:164:83)
E               at doWrite (/home/punix/sifnode/smart-contracts/node_modules/winston/node_modules/readable-stream/lib/_stream_writable.js:409:139)
E               at writeOrBuffer (/home/punix/sifnode/smart-contracts/node_modules/winston/node_modules/readable-stream/lib/_stream_writable.js:398:5)
E               at DerivedLogger.Writable.write (/home/punix/sifnode/smart-contracts/node_modules/winston/node_modules/readable-stream/lib/_stream_writable.js:307:11)
E               at DerivedLogger.log (/home/punix/sifnode/smart-contracts/node_modules/winston/lib/winston/logger.js:210:12)
E               at ExceptionHandler._uncaughtException (/home/punix/sifnode/smart-contracts/node_modules/winston/lib/winston/exception-handler.js:220:17)
E               at process.emit (events.js:400:28)
E           Emitted 'error' event on PassThrough instance at:
E               at errorOrDestroy (/home/punix/sifnode/smart-contracts/node_modules/winston/node_modules/readable-stream/lib/internal/streams/destroy.js:98:101)
E               at writeAfterEnd (/home/punix/sifnode/smart-contracts/node_modules/winston/node_modules/readable-stream/lib/_stream_writable.js:263:3)
E               at PassThrough.Writable.write (/home/punix/sifnode/smart-contracts/node_modules/winston/node_modules/readable-stream/lib/_stream_writable.js:305:21)
E               [... lines matching original stack trace ...]
E               at ExceptionHandler._uncaughtException (/home/punix/sifnode/smart-contracts/node_modules/winston/lib/winston/exception-handler.js:220:17)

src/py/test_utilities.py:138: Exception

**Comment by daniportugalgit** [comment]
@sheokapr 
To solve this issue, please export another variable before running `. $BASEDIR/test/integration/environment_setup.sh`:

```
export WEB3_PROVIDER=wss://eth-ropsten.alchemyapi.io/v2/ALCHEMY-ID
```

I left the correct ALCHEMY-ID in Slack for you (it's the same that @intl-man posted there).
