### ISSUE TITLE
 Determine appropriate steps for spinning up a new IBC chain

### ISSUE THREAD

**Issue by pandaring2you** [Sifchain/sifnode#2546]
Investigate panic errors on tempnet with Lance and determine the process for spinning up a new IBC chain going forward with approval by chainops. 

Using sifnode repo with the branch `feature/pmtp`, deploying a tempnet instance against this branch throws a panic error with the following logs:

```
token_registry % kubectl logs -n feature-pmtp sifnode-9d7fb98fc-qt2dj
10:02PM INF Configuration is valid:
Configurable Values:
  DAEMON_HOME: /root/.sifnoded
  DAEMON_NAME: sifnoded
  DAEMON_ALLOW_DOWNLOAD_BINARIES: true
  DAEMON_RESTART_AFTER_UPGRADE: true
  DAEMON_POLL_INTERVAL: 300ms
  UNSAFE_SKIP_BACKUP: true
  DAEMON_PREUPGRADE_MAX_RETRIES: 0
Derived Values:
        Root Dir: /root/.sifnoded/cosmovisor
     Upgrade Dir: /root/.sifnoded/cosmovisor/upgrades
     Genesis Bin: /root/.sifnoded/cosmovisor/genesis/bin/sifnoded
  Monitored File: /root/.sifnoded/data/upgrade-info.json
 module=cosmovisor
10:02PM INF running app args=["start","--rpc.laddr","tcp://0.0.0.0:26657","--minimum-gas-prices","0.5rowan","--x-crisis-skip-assert-invariants","--inv-check-period","600"] module=cosmovisor path=/root/.sifnoded/cosmovisor/genesis/bin/sifnoded
10:02PM ERR failed to read error="lstat /root/.sifnoded/cosmovisor/current/upgrade-info.json: no such file or directory" filename=/root/.sifnoded/cosmovisor/current/upgrade-info.json module=cosmovisor
10:02PM INF starting ABCI with Tendermint
10:02PM INF Starting multiAppConn service impl=multiAppConn module=proxy
10:02PM INF Starting localClient service connection=query impl=localClient module=abci-client
10:02PM INF Starting localClient service connection=snapshot impl=localClient module=abci-client
10:02PM INF Starting localClient service connection=mempool impl=localClient module=abci-client
10:02PM INF Starting localClient service connection=consensus impl=localClient module=abci-client
10:02PM INF Starting EventBus service impl=EventBus module=events
10:02PM INF Starting PubSub service impl=PubSub module=pubsub
10:02PM INF Starting IndexerService service impl=IndexerService module=txindex
10:02PM INF ABCI Handshake App Info hash= height=0 module=consensus protocol-version=0 software-version=0.10.1
10:02PM INF ABCI Replay Blocks appHeight=0 module=consensus stateHeight=0 storeHeight=0
10:02PM INF created new capability module=ibc name=ports/transfer
10:02PM INF port binded module=x/ibc/port port=transfer
10:02PM INF claimed capability capability=1 module=transfer name=ports/transfer
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x110723d]

goroutine 1 [running]:
math/big.(*Int).Sign(...)
	/usr/local/go/src/math/big/int.go:39
github.com/cosmos/cosmos-sdk/types.Dec.IsNegative(...)
	/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.43.0/types/decimal.go:203
github.com/Sifchain/sifnode/x/clp/types.validatePmtpPeriodGovernanceRate({0x1b49a80, 0x0})
	/sifchain/x/clp/types/params.go:111 +0x3d
github.com/cosmos/cosmos-sdk/x/params/types.Subspace.SetParamSet({{0x2057698, 0xc0013dc320}, 0xc0004fc1e0, {0x1ffd558, 0xc000ea0210}, {0x1ffd5a8, 0xc000ea0320}, {0xc0013dba20, 0x3, 0x1b}, ...}, ...)
	/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.43.0/x/params/types/subspace.go:236 +0x185
github.com/Sifchain/sifnode/x/clp/keeper.Keeper.SetParams(...)
	/sifchain/x/clp/keeper/params.go:40
github.com/Sifchain/sifnode/x/clp.InitGenesis({{0x2030988, 0xc000056040}, {0x205c9e0, 0xc000db5c40}, {{0x0, 0x0}, {0xc0002080f0, 0x18}, 0x0, {0x2a569d5e, ...}, ...}, ...}, ...)
	/sifchain/x/clp/genesis.go:17 +0x185
github.com/Sifchain/sifnode/x/clp.AppModule.InitGenesis({{}, {{0x1ffd558, 0xc000ea02e0}, {0x2057698, 0xc0013dc320}, {0x7f1120ac63f8, 0xc001309600}, {0x1fff0d8, 0xc0011fa7e0}, {0x7f1120ac7498, ...}, ...}, ...}, ...)
	/sifchain/x/clp/module.go:142 +0x13b
github.com/cosmos/cosmos-sdk/types/module.(*Manager).InitGenesis(_, {{0x2030988, 0xc000056040}, {0x205c9e0, 0xc000db5c40}, {{0x0, 0x0}, {0xc0002080f0, 0x18}, 0x0, ...}, ...}, ...)
	/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.43.0/types/module/module.go:306 +0x29d
github.com/Sifchain/sifnode/app.(*SifchainApp).InitChainer(_, {{0x2030988, 0xc000056040}, {0x205c9e0, 0xc000db5c40}, {{0x0, 0x0}, {0xc0002080f0, 0x18}, 0x0, ...}, ...}, ...)
	/sifchain/app/app.go:561 +0x1d2
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).InitChain(0xc000583860, {{0x2a569d5e, 0xed9c1bcda, 0x0}, {0xc0002080f0, 0x18}, 0xc000cf9560, {0x2f64c38, 0x0, 0x0}, ...})
	/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.43.0/baseapp/abci.go:62 +0x475
github.com/tendermint/tendermint/abci/client.(*localClient).InitChainSync(0xc000225980, {{0x2a569d5e, 0xed9c1bcda, 0x0}, {0xc0002080f0, 0x18}, 0xc000cf9560, {0x2f64c38, 0x0, 0x0}, ...})
	/go/pkg/mod/github.com/tendermint/tendermint@v0.34.14/abci/client/local_client.go:272 +0x118
github.com/tendermint/tendermint/proxy.(*appConnConsensus).InitChainSync(0xae, {{0x2a569d5e, 0xed9c1bcda, 0x0}, {0xc0002080f0, 0x18}, 0xc000cf9560, {0x2f64c38, 0x0, 0x0}, ...})
	/go/pkg/mod/github.com/tendermint/tendermint@v0.34.14/proxy/app_conn.go:77 +0x55
github.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(_, {{{0xb, 0x0}, {0x1b6c32d, 0x7}}, {0xc0002080f0, 0x18}, 0x1, 0x0, {{0x0, ...}, ...}, ...}, ...)
	/go/pkg/mod/github.com/tendermint/tendermint@v0.34.14/consensus/replay.go:319 +0xd98
github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0xc001039e18, {0x205de48, 0xc0000b8410})
	/go/pkg/mod/github.com/tendermint/tendermint@v0.34.14/consensus/replay.go:268 +0x3c8
github.com/tendermint/tendermint/node.doHandshake({_, _}, {{{0xb, 0x0}, {0x1b6c32d, 0x7}}, {0xc0002080f0, 0x18}, 0x1, 0x0, ...}, ...)
	/go/pkg/mod/github.com/tendermint/tendermint@v0.34.14/node/node.go:325 +0x1b8
github.com/tendermint/tendermint/node.NewNode(0xc001229680, {0x200d580, 0xc001330c80}, 0xc000152050, {0x1feef20, 0xc00000c870}, 0x0, 0x0, 0xc000152480, {0x20316e0, ...}, ...)
	/go/pkg/mod/github.com/tendermint/tendermint@v0.34.14/node/node.go:733 +0x578
github.com/cosmos/cosmos-sdk/server.startInProcess(_, {{0x0, 0x0, 0x0}, {0x206e3b8, 0xc001307470}, {0x0, 0x0}, {0x2039b30, 0xc00121c2d0}, ...}, ...)
	/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.43.0/server/start.go:263 +0x7c5
github.com/cosmos/cosmos-sdk/server.StartCmd.func2(0xc001250c80, {0xc0011fd490, 0x0, 0x7})
	/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.43.0/server/start.go:129 +0x193
github.com/spf13/cobra.(*Command).execute(0xc001250c80, {0xc0011fd420, 0x7, 0x7})
	/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:856 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0xc0011c2f00)
	/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:902
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:895
github.com/cosmos/cosmos-sdk/server/cmd.Execute(0x1, {0xc0012162c0, 0xf})
	/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.43.0/server/cmd/execute.go:36 +0x1eb
main.main()
	/sifchain/cmd/sifnoded/main.go:18 +0x45
10:02PM ERR  error="exit status 2" module=cosmovisor
```

The error can be reproduced locally using the following commands:

```
sifgen node create sifchain-1 sifnode1 "connect rocket hat athlete kind fall auction measure wage father bridge tackle midnight athlete benefit faculty shove okay win entire reveal kit era truly" \
--admin-clp-addresses="sif1mxv2xmhm9r25cdxpwp4n43fd98t8xz97mg6xyt|sif1rkl3p87fanf8srn44lp9xrxx8smtux4mfjhwf2" \
--admin-oracle-address=sif1mxv2xmhm9r25cdxpwp4n43fd98t8xz97mg6xyt \
--standalone --with-cosmovisor
```

```
export DAEMON_NAME=sifnoded
export DAEMON_HOME=$HOME/.sifnoded
export DAEMON_ALLOW_DOWNLOAD_BINARIES=true
export DAEMON_RESTART_AFTER_UPGRADE=true
export UNSAFE_SKIP_BACKUP=true
```

```
cosmovisor start --rpc.laddr tcp://0.0.0.0:26657
```

```
$ cosmovisor start --rpc.laddr tcp://0.0.0.0:26657 --x-crisis-skip-assert-invariants
4:41PM WRN Use of cosmovisor without the 'run' command is deprecated. Use: cosmovisor run [args] module=cosmovisor
4:41PM INF running app args=["start","--rpc.laddr","tcp://0.0.0.0:26657","--x-crisis-skip-assert-invariants"] module=cosmovisor path=/home/caner/.sifnoded/cosmovisor/genesis/bin/sifnoded
4:41PM ERR failed to read error="lstat /home/caner/.sifnoded/cosmovisor/current/upgrade-info.json: no such file or directory" filename=/home/caner/.sifnoded/cosmovisor/current/upgrade-info.json module=cosmovisor
4:41PM INF starting ABCI with Tendermint
4:41PM ERR WARNING: The minimum-gas-prices config in app.toml is set to the empty string. This defaults to 0 in the current version, but will error in the next version (SDK v0.44). Please explicitly put the desired minimum-gas-prices in your app.toml.
4:41PM INF Starting multiAppConn service impl=multiAppConn module=proxy
4:41PM INF Starting localClient service connection=query impl=localClient module=abci-client
4:41PM INF Starting localClient service connection=snapshot impl=localClient module=abci-client
4:41PM INF Starting localClient service connection=mempool impl=localClient module=abci-client
4:41PM INF Starting localClient service connection=consensus impl=localClient module=abci-client
4:41PM INF Starting EventBus service impl=EventBus module=events
4:41PM INF Starting PubSub service impl=PubSub module=pubsub
4:41PM INF Starting IndexerService service impl=IndexerService module=txindex
4:41PM INF ABCI Handshake App Info hash= height=0 module=consensus protocol-version=0 software-version=0.10.1
4:41PM INF ABCI Replay Blocks appHeight=0 module=consensus stateHeight=0 storeHeight=0
4:41PM INF created new capability module=ibc name=ports/transfer
4:41PM INF port binded module=x/ibc/port port=transfer
4:41PM INF claimed capability capability=1 module=transfer name=ports/transfer
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x110b8fd]

goroutine 1 [running]:
math/big.(*Int).Sign(...)
	/usr/local/go/src/math/big/int.go:39
github.com/cosmos/cosmos-sdk/types.Dec.IsNegative(...)
	/home/caner/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.43.0/types/decimal.go:203
github.com/Sifchain/sifnode/x/clp/types.validatePmtpPeriodGovernanceRate({0x1b4ef80, 0x0})
	/home/caner/Dev/sifchain/pmtp-implementation/x/clp/types/params.go:111 +0x3d
github.com/cosmos/cosmos-sdk/x/params/types.Subspace.SetParamSet({{0x205d1b8, 0xc000da5e90}, 0xc000036650, {0x2002d38, 0xc000dadce0}, {0x2002d88, 0xc000daddf0}, {0xc00118dee0, 0x3, 0x1b}, ...}, ...)
	/home/caner/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.43.0/x/params/types/subspace.go:236 +0x185
github.com/Sifchain/sifnode/x/clp/keeper.Keeper.SetParams(...)
	/home/caner/Dev/sifchain/pmtp-implementation/x/clp/keeper/params.go:40
github.com/Sifchain/sifnode/x/clp.InitGenesis({{0x20361c8, 0xc0000520d8}, {0x2062500, 0xc00002ac00}, {{0x0, 0x0}, {0xc0000302a0, 0xa}, 0x0, {0x167add06, ...}, ...}, ...}, ...)
	/home/caner/Dev/sifchain/pmtp-implementation/x/clp/genesis.go:17 +0x185
github.com/Sifchain/sifnode/x/clp.AppModule.InitGenesis({{}, {{0x2002d38, 0xc000daddb0}, {0x205d1b8, 0xc000da5e90}, {0x7f5304088558, 0xc00121d4a0}, {0x20048b8, 0xc0001cccf0}, {0x7f53040885a8, ...}, ...}, ...}, ...)
	/home/caner/Dev/sifchain/pmtp-implementation/x/clp/module.go:142 +0x13b
github.com/cosmos/cosmos-sdk/types/module.(*Manager).InitGenesis(_, {{0x20361c8, 0xc0000520d8}, {0x2062500, 0xc00002ac00}, {{0x0, 0x0}, {0xc0000302a0, 0xa}, 0x0, ...}, ...}, ...)
	/home/caner/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.43.0/types/module/module.go:306 +0x29d
github.com/Sifchain/sifnode/app.(*SifchainApp).InitChainer(_, {{0x20361c8, 0xc0000520d8}, {0x2062500, 0xc00002ac00}, {{0x0, 0x0}, {0xc0000302a0, 0xa}, 0x0, ...}, ...}, ...)
	/home/caner/Dev/sifchain/pmtp-implementation/app/app.go:561 +0x1d2
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).InitChain(0xc000d6b1e0, {{0x167add06, 0xed9c54d8b, 0x0}, {0xc0000302a0, 0xa}, 0xc00002e960, {0x2f75ef8, 0x0, 0x0}, ...})
	/home/caner/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.43.0/baseapp/abci.go:62 +0x475
github.com/tendermint/tendermint/abci/client.(*localClient).InitChainSync(0xc00017a900, {{0x167add06, 0xed9c54d8b, 0x0}, {0xc0000302a0, 0xa}, 0xc00002e960, {0x2f75ef8, 0x0, 0x0}, ...})
	/home/caner/go/pkg/mod/github.com/tendermint/tendermint@v0.34.14/abci/client/local_client.go:272 +0x118
github.com/tendermint/tendermint/proxy.(*appConnConsensus).InitChainSync(0xb3, {{0x167add06, 0xed9c54d8b, 0x0}, {0xc0000302a0, 0xa}, 0xc00002e960, {0x2f75ef8, 0x0, 0x0}, ...})
	/home/caner/go/pkg/mod/github.com/tendermint/tendermint@v0.34.14/proxy/app_conn.go:77 +0x55
github.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(_, {{{0xb, 0x0}, {0x1b7181e, 0x7}}, {0xc0000302a0, 0xa}, 0x1, 0x0, {{0x0, ...}, ...}, ...}, ...)
	/home/caner/go/pkg/mod/github.com/tendermint/tendermint@v0.34.14/consensus/replay.go:319 +0xd98
github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0xc000f59e18, {0x2063968, 0xc0001da340})
	/home/caner/go/pkg/mod/github.com/tendermint/tendermint@v0.34.14/consensus/replay.go:268 +0x3c8
github.com/tendermint/tendermint/node.doHandshake({_, _}, {{{0xb, 0x0}, {0x1b7181e, 0x7}}, {0xc0000302a0, 0xa}, 0x1, 0x0, ...}, ...)
	/home/caner/go/pkg/mod/github.com/tendermint/tendermint@v0.34.14/node/node.go:325 +0x1b8
github.com/tendermint/tendermint/node.NewNode(0xc000b7f040, {0x2012db8, 0xc000b90f00}, 0xc000dc3d50, {0x1ff45e0, 0xc000560cd8}, 0x0, 0x0, 0xc000dc3eb0, {0x2036f20, ...}, ...)
	/home/caner/go/pkg/mod/github.com/tendermint/tendermint@v0.34.14/node/node.go:733 +0x578
github.com/cosmos/cosmos-sdk/server.startInProcess(_, {{0x0, 0x0, 0x0}, {0x2073ed8, 0xc000b89140}, {0x0, 0x0}, {0x203f5f0, 0xc001126a60}, ...}, ...)
	/home/caner/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.43.0/server/start.go:263 +0x7c5
github.com/cosmos/cosmos-sdk/server.StartCmd.func2(0xc001170c80, {0xc0012269f0, 0x0, 0x3})
	/home/caner/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.43.0/server/start.go:129 +0x193
github.com/spf13/cobra.(*Command).execute(0xc001170c80, {0xc001226990, 0x3, 0x3})
	/home/caner/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:856 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0xc0010c4f00)
	/home/caner/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
	/home/caner/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:902
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	/home/caner/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:895
github.com/cosmos/cosmos-sdk/server/cmd.Execute(0x1, {0xc000057e00, 0x15})
	/home/caner/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.43.0/server/cmd/execute.go:36 +0x1eb
main.main()
	/home/caner/Dev/sifchain/pmtp-implementation/cmd/sifnoded/main.go:18 +0x45
4:41PM WRN Use of cosmovisor without the 'run' command is deprecated. Use: cosmovisor run [args] module=cosmovisor
4:41PM ERR  error="exit status 2" module=cosmovisor
```

The error also happens when using `sifgen` without `cosmovisor` as follow:

```
sifgen node create sifchain-1 sifnode1 "connect rocket hat athlete kind fall auction measure wage father bridge tackle midnight athlete benefit faculty shove okay win entire reveal kit era truly" \
--admin-clp-addresses="sif1mxv2xmhm9r25cdxpwp4n43fd98t8xz97mg6xyt|sif1rkl3p87fanf8srn44lp9xrxx8smtux4mfjhwf2" \
--admin-oracle-address=sif1mxv2xmhm9r25cdxpwp4n43fd98t8xz97mg6xyt \
--standalone
```

```
sifnoded start
```

but when using `sifnoded init` and `sifnoded start` with the following scripts, the panic error does not occur and the chain is started with success:

* `init.sh`: https://github.com/Sifchain/sifnode/blob/develop/scripts/init.sh
* `run.sh`: https://github.com/Sifchain/sifnode/blob/develop/scripts/run.sh

**Comment by pandaring2you** [comment]
Resolved
