### ISSUE TITLE
Python load test dependency failure

### ISSUE THREAD

**Issue by jzvikart** [Sifchain/sifnode#3059]
Reported by @sifag:

Trying to install load testing tool's dependencies using 3.9 breaks.
OS: 
`Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.4 LTS
Release:	20.04
Codename:	focal`

To reproduce from the sifnode main directory: `rm -rf test/integration/framework/venv; python3.9 test/integration/framework/siftool`

Output
> Initializing Python virtual environment on first use in '/home/user/code/sifnode/test/integration/framework/venv'...
> Collecting pip
>   Using cached pip-22.2-py3-none-any.whl (2.0 MB)
> Installing collected packages: pip
>   Attempting uninstall: pip
>     Found existing installation: pip 20.0.2
>     Uninstalling pip-20.0.2:
>       Successfully uninstalled pip-20.0.2
> Successfully installed pip-22.2
> Collecting wheel
>   Using cached wheel-0.37.1-py2.py3-none-any.whl (35 kB)
> Installing collected packages: wheel
> Successfully installed wheel-0.37.1
> Collecting grpcio-tools==1.47.0
>   Using cached grpcio_tools-1.47.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.4 MB)
> Collecting pytest==7.1.2
>   Using cached pytest-7.1.2-py3-none-any.whl (297 kB)
> Collecting PyYAML==6.0
>   Using cached PyYAML-6.0-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (701 kB)
> Collecting rusty-rlp==0.2.1
>   Using cached rusty_rlp-0.2.1-cp38-cp38-manylinux1_x86_64.whl (177 kB)
> Collecting web3==5.29.2
>   Using cached web3-5.29.2-py3-none-any.whl (500 kB)
> Requirement already satisfied: setuptools in ./test/integration/framework/venv/lib/python3.8/site-packages (from grpcio-tools==1.47.0->-r /home/user/code/sifnode/test/integration/framework/requirements.txt (line 1)) (44.0.0)
> Collecting grpcio>=1.47.0
>   Using cached grpcio-1.47.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.5 MB)
> Collecting protobuf<4.0dev,>=3.12.0
>   Using cached protobuf-3.20.1-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.whl (1.0 MB)
> Collecting packaging
>   Using cached packaging-21.3-py3-none-any.whl (40 kB)
> Collecting iniconfig
>   Using cached iniconfig-1.1.1-py2.py3-none-any.whl (5.0 kB)
> Collecting attrs>=19.2.0
>   Using cached attrs-21.4.0-py2.py3-none-any.whl (60 kB)
> Collecting pluggy<2.0,>=0.12
>   Using cached pluggy-1.0.0-py2.py3-none-any.whl (13 kB)
> Collecting tomli>=1.0.0
>   Using cached tomli-2.0.1-py3-none-any.whl (12 kB)
> Collecting py>=1.8.2
>   Using cached py-1.11.0-py2.py3-none-any.whl (98 kB)
> Collecting eth-hash[pycryptodome]<1.0.0,>=0.2.0
>   Using cached eth_hash-0.5.0-py3-none-any.whl (8.9 kB)
> Collecting eth-utils<2.0.0,>=1.9.5
>   Using cached eth_utils-1.10.0-py3-none-any.whl (24 kB)
> Collecting eth-account<0.6.0,>=0.5.7
>   Using cached eth_account-0.5.8-py3-none-any.whl (101 kB)
> Collecting ipfshttpclient==0.8.0a2
>   Using cached ipfshttpclient-0.8.0a2-py3-none-any.whl (82 kB)
> Collecting lru-dict<2.0.0,>=1.1.6
>   Using cached lru_dict-1.1.8-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (29 kB)
> Collecting hexbytes<1.0.0,>=0.1.0
>   Using cached hexbytes-0.2.2-py3-none-any.whl (6.1 kB)
> Collecting requests<3.0.0,>=2.16.0
>   Using cached requests-2.28.1-py3-none-any.whl (62 kB)
> Collecting eth-typing<3.0.0,>=2.0.0
>   Using cached eth_typing-2.3.0-py3-none-any.whl (6.2 kB)
> Collecting aiohttp<4,>=3.7.4.post0
>   Using cached aiohttp-3.8.1-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (1.3 MB)
> Collecting websockets<10,>=9.1
>   Using cached websockets-9.1-cp38-cp38-manylinux2010_x86_64.whl (102 kB)
> Collecting eth-abi<3.0.0,>=2.0.0b6
>   Using cached eth_abi-2.2.0-py3-none-any.whl (28 kB)
> Collecting jsonschema<5,>=3.2.0
>   Using cached jsonschema-4.7.2-py3-none-any.whl (81 kB)
> Collecting multiaddr>=0.0.7
>   Using cached multiaddr-0.0.9-py2.py3-none-any.whl (16 kB)
> Collecting charset-normalizer<3.0,>=2.0
>   Using cached charset_normalizer-2.1.0-py3-none-any.whl (39 kB)
> Collecting frozenlist>=1.1.1
>   Using cached frozenlist-1.3.0-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (158 kB)
> Collecting multidict<7.0,>=4.5
>   Using cached multidict-6.0.2-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (121 kB)
> Collecting aiosignal>=1.1.2
>   Using cached aiosignal-1.2.0-py3-none-any.whl (8.2 kB)
> Collecting yarl<2.0,>=1.0
>   Using cached yarl-1.7.2-cp38-cp38-

> manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (308 kB)
> Collecting async-timeout<5.0,>=4.0.0a3
>   Using cached async_timeout-4.0.2-py3-none-any.whl (5.8 kB)
> Collecting parsimonious<0.9.0,>=0.8.0
>   Using cached parsimonious-0.8.1-py3-none-any.whl
> Collecting eth-keyfile<0.6.0,>=0.5.0
>   Using cached eth_keyfile-0.5.1-py3-none-any.whl (8.3 kB)
> Collecting bitarray<3,>=1.2.1
>   Using cached bitarray-2.6.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (241 kB)
> Collecting eth-rlp<2,>=0.1.2
>   Using cached eth_rlp-0.3.0-py3-none-any.whl (5.0 kB)
> Collecting eth-keys<0.4.0,>=0.3.4
>   Using cached eth_keys-0.3.4-py3-none-any.whl (21 kB)
> Collecting rlp<3,>=1.0.0
>   Using cached rlp-2.0.1-py2.py3-none-any.whl (20 kB)
> Collecting pycryptodome<4,>=3.6.6
>   Using cached pycryptodome-3.15.0-cp35-abi3-manylinux2010_x86_64.whl (2.3 MB)
> Collecting cytoolz<1.0.0,>=0.10.1
>   Using cached cytoolz-0.12.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.8 MB)
> Collecting eth-utils<2.0.0,>=1.9.5
>   Using cached eth_utils-1.9.5-py3-none-any.whl (23 kB)
> Collecting six>=1.5.2
>   Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
> Collecting pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0
>   Using cached pyrsistent-0.18.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (119 kB)
> Collecting importlib-resources>=1.4.0
>   Using cached importlib_resources-5.9.0-py3-none-any.whl (33 kB)
> Collecting urllib3<1.27,>=1.21.1
>   Using cached urllib3-1.26.10-py2.py3-none-any.whl (139 kB)
> Collecting idna<4,>=2.5
>   Using cached idna-3.3-py3-none-any.whl (61 kB)
> Collecting certifi>=2017.4.17
>   Using cached certifi-2022.6.15-py3-none-any.whl (160 kB)
> Collecting pyparsing!=3.0.5,>=2.0.2
>   Using cached pyparsing-3.0.9-py3-none-any.whl (98 kB)
> Collecting toolz>=0.8.0
>   Using cached toolz-0.12.0-py3-none-any.whl (55 kB)
> Collecting eth-rlp<2,>=0.1.2
>   Using cached eth_rlp-0.2.1-py3-none-any.whl (5.0 kB)
> Collecting zipp>=3.1.0
>   Using cached zipp-3.8.1-py3-none-any.whl (5.6 kB)
> Collecting base58
>   Using cached base58-2.1.1-py3-none-any.whl (5.6 kB)
> Collecting netaddr
>   Using cached netaddr-0.8.0-py2.py3-none-any.whl (1.9 MB)
> Collecting varint
>   Using cached varint-1.0.2-py3-none-any.whl
> Installing collected packages: varint, rusty-rlp, netaddr, lru-dict, iniconfig, bitarray, zipp, websockets, urllib3, toolz, tomli, six, PyYAML, pyrsistent, pyparsing, pycryptodome, py, protobuf, pluggy, multidict, idna, hexbytes, frozenlist, eth-typing, eth-hash, charset-normalizer, certifi, base58, attrs, async-timeout, yarl, requests, parsimonious, packaging, multiaddr, importlib-resources, grpcio, cytoolz, aiosignal, pytest, jsonschema, ipfshttpclient, grpcio-tools, eth-utils, aiohttp, rlp, eth-keys, eth-abi, eth-rlp, eth-keyfile, eth-account, web3
> Successfully installed PyYAML-6.0 aiohttp-3.8.1 aiosignal-1.2.0 async-timeout-4.0.2 attrs-21.4.0 base58-2.1.1 bitarray-2.6.0 certifi-2022.6.15 charset-normalizer-2.1.0 cytoolz-0.12.0 eth-abi-2.2.0 eth-account-0.5.8 eth-hash-0.5.0 eth-keyfile-0.5.1 eth-keys-0.3.4 eth-rlp-0.2.1 eth-typing-2.3.0 eth-utils-1.9.5 frozenlist-1.3.0 grpcio-1.47.0 grpcio-tools-1.47.0 hexbytes-0.2.2 idna-3.3 importlib-resources-5.9.0 iniconfig-1.1.1 ipfshttpclient-0.8.0a2 jsonschema-4.7.2 lru-dict-1.1.8 multiaddr-0.0.9 multidict-6.0.2 netaddr-0.8.0 packaging-21.3 parsimonious-0.8.1 pluggy-1.0.0 protobuf-3.20.1 py-1.11.0 pycryptodome-3.15.0 pyparsing-3.0.9 pyrsistent-0.18.1 pytest-7.1.2 requests-2.28.1 rlp-2.0.1 rusty-rlp-0.2.1 six-1.16.0 tomli-2.0.1 toolz-0.12.0 urllib3-1.26.10 varint-1.0.2 web3-5.29.2 websockets-9.1 yarl-1.7.2 zipp-3.8.1
> Traceback (most recent call last):
>   File "/home/user/code/sifnode/test/integration/framework/siftool", line 77, in <module>
>     main(sys.argv[1:])
>   File "/home/user/code/sifnode/test/integration/framework/siftool", line 72, in main
>     main_module = load_main_module()
>   File "/home/user/code/sifnode/test/integration/framework/siftool", line 67, in load_main_module
>     import siftool.main as siftool_main
>   File "/home/user/code/sifnode/test/integration/framework/src/siftool/main.py", line 5, in <module>
>     from siftool import test_utils, run_env, cosmos
>   File "/home/user/code/sifnode/test/integration/framework/src/siftool/test_utils.py", line 8, in <module>
>     import web3
>   File "/home/user/code/sifnode/test/integration/framework/venv/lib/python3.8/site-packages/web3/__init__.py", line 6, in <module>
>     from eth_account import (
>   File "/home/user/code/sifnode/test/integration/framework/venv/lib/python3.8/site-packages/eth_account/__init__.py", line 1, in <module>
>     from eth_account.account import (
>   File "/home/user/code/sifnode/test/integration/framework/venv/lib/python3.8/site-packages/eth_account/account.py", line 8, in <module>
>     from cytoolz import (
>   File "/home/user/code/sifnode/test/integration/framework/venv/lib/python3.8/site-packages/cytoolz/__init__.py", line 1, in <module>
>     from .itertoolz import *
> ModuleNotFoundError: No module named 'cytoolz.itertoolz'

**Comment by jzvikart** [comment]
> user@machine:~/code/sifnode$ echo $PATH 
/home/user/.cabal/bin:/home/user/.ghcup/bin:/home/user/.opam/default/bin:/home/user/.cargo/bin:/home/user/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/user/.local/bin:/usr/local/go/bin://home/user/go/bin

**Comment by jzvikart** [comment]
Note to self: Python 3.9 was installed using `apt-get`. Try to make it work on 3.8 (avoid `|` for dicts, check dependencies, add version check etc.)

**Comment by jzvikart** [comment]
Fixed, test tested working on python 3.8.10.
