### ISSUE TITLE
[Peggy] - Error: Cannot find module 'dotenv'

### ISSUE THREAD

**Issue by EddCS** [Sifchain/sifnode#387]
**Describe the bug**
Build error when running `yarn migrate`

**Bug Reproduction Steps**
```
./scripts/init.sh
cd smart-contracts
yarn develop
yarn migrate
```

**Stack trace**
```
yarn migrate       
                                                                                                                   
yarn run v1.22.4
$ npx truffle migrate --reset
Error: Cannot find module 'dotenv'
Require stack:
- /home/edd/Workspace/Sifchain/i341/smart-contracts/truffle-config.js
- /usr/local/lib/node_modules/truffle/node_modules/original-require/index.js
- /usr/local/lib/node_modules/truffle/build/cli.bundled.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:15)
    at Function.Module._load (node:internal/modules/cjs/loader:763:27)
    at Module.require (node:internal/modules/cjs/loader:991:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (/home/edd/Workspace/Sifchain/i341/smart-contracts/truffle-config.js:1:1)
    at Module._compile (node:internal/modules/cjs/loader:1102:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1131:10)
    at Module.load (node:internal/modules/cjs/loader:967:32)
    at Function.Module._load (node:internal/modules/cjs/loader:807:14)
    at Module.require (node:internal/modules/cjs/loader:991:19)
    at Object.require (node:internal/modules/cjs/helpers:92:18)
    at Function.load (/usr/local/lib/node_modules/truffle/build/webpack:/packages/config/dist/index.js:161:1)
    at Function.detect (/usr/local/lib/node_modules/truffle/build/webpack:/packages/config/dist/index.js:150:1)
    at Object.run (/usr/local/lib/node_modules/truffle/build/webpack:/packages/core/lib/commands/migrate.js:199:1)
    at Command.run (/usr/local/lib/node_modules/truffle/build/webpack:/packages/core/lib/command.js:136:1)
    at Object.<anonymous> (/usr/local/lib/node_modules/truffle/build/webpack:/packages/core/cli.js:56:1)
    at __webpack_require__ (/usr/local/lib/node_modules/truffle/build/webpack:/webpack/bootstrap:19:1)
    at /usr/local/lib/node_modules/truffle/build/webpack:/webpack/bootstrap:83:1
    at Object.<anonymous> (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:89:10)
    at Module._compile (node:internal/modules/cjs/loader:1102:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1131:10)
    at Module.load (node:internal/modules/cjs/loader:967:32)
    at Function.Module._load (node:internal/modules/cjs/loader:807:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
    at /usr/local/lib/node_modules/npm/node_modules/libnpx/index.js:268:14
Truffle v5.1.55 (core: 5.1.55)
Node v15.3.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Fixed by running `npm install dotenv && yarn migrate` so I suspect we need to add `dotenv` to our `yarn` config.

**Comment by utx0** [comment]
Looks like you missed the `yarn install` step... ?

**Comment by jkbrooks** [comment]
@EddCS 
Is @utx0 correct?  If so, please close this bug, if not, please confirm.

**Comment by utx0** [comment]
Just tested locally. Not an issue. `"dotenv": "^8.1.0"` is also in the package.json file

**Comment by eldruid** [comment]
did anyone come a fix for this?

i am experiencing same output.

**Comment by ivanlondono** [comment]
`npm install dotenv`
or
`npm install --dotenv-extended`
