### ISSUE TITLE
Errno::ENOENT: No such file or directory - sifgen

### ISSUE THREAD

**Issue by lufa23** [Sifchain/sifnode#644]
When launching `rake "keys:generate:mnemonic"` in the `sifnode` folder i get the following logs:

```
** Invoke keys:generate:mnemonic (first_time)
** Execute keys:generate:mnemonic
rake aborted!
Errno::ENOENT: No such file or directory - sifgen
/..................../Sifchain/sifnode/deploy/rake/keys.rake:7:in ``'
/...................../Sifchain/sifnode/deploy/rake/keys.rake:7:in `block (3 levels) in <top (required)>'
/Library/Ruby/Gems/2.3.0/gems/rake-10.4.2/lib/rake/task.rb:240:in `block in execute'
/Library/Ruby/Gems/2.3.0/gems/rake-10.4.2/lib/rake/task.rb:235:in `each'
/Library/Ruby/Gems/2.3.0/gems/rake-10.4.2/lib/rake/task.rb:235:in `execute'
/Library/Ruby/Gems/2.3.0/gems/rake-10.4.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/Library/Ruby/Gems/2.3.0/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/Library/Ruby/Gems/2.3.0/gems/rake-10.4.2/lib/rake/task.rb:165:in `invoke'
/Library/Ruby/Gems/2.3.0/gems/rake-10.4.2/lib/rake/application.rb:150:in `invoke_task'
/Library/Ruby/Gems/2.3.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/Library/Ruby/Gems/2.3.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `each'
/Library/Ruby/Gems/2.3.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `block in top_level'
/Library/Ruby/Gems/2.3.0/gems/rake-10.4.2/lib/rake/application.rb:115:in `run_with_threads'
/Library/Ruby/Gems/2.3.0/gems/rake-10.4.2/lib/rake/application.rb:100:in `top_level'
/Library/Ruby/Gems/2.3.0/gems/rake-10.4.2/lib/rake/application.rb:78:in `block in run'
/Library/Ruby/Gems/2.3.0/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
/Library/Ruby/Gems/2.3.0/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'
/Library/Ruby/Gems/2.3.0/gems/rake-10.4.2/bin/rake:33:in `<top (required)>'
/usr/bin/rake:22:in `load'
/usr/bin/rake:22:in `<main>'
Tasks: TOP => keys:generate:mnemonic
```
Just before launching `rake "keys:generate:mnemonic"`, I have successfully deployed the Kubernetes cluster, as launching `rake "cluster:deploy[merry-go-round,aws]"`shows the following logs:
```
Apply complete! Resources: 36 added, 0 changed, 0 destroyed.
.......... sifnode/deploy/rake/../../.live/sifchain-aws-merry-go-round created successfully
```

What could be the problem?

Thanks

**Comment by utx0** [comment]
You havent setup you local shell completely. As pre the readme you need the following set in your shell:

```
export GOPATH=~/go to your shell
export PATH=$PATH:$GOPATH/bin to your shell
```
